### ISSUE TITLE
gitbook install error

### ISSUE THREAD

**Issue by nicolasxu** [GitbookIO/plugin-autocover#21]
I got the following error when install autocover

installing plugin "autocover"
postinstall:sunlight-x    ▐ ╢███████████████████████████████████████░░░░░░╟
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at spawn (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/shenxinxu/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)

**Comment by wangzw** [comment]
I got the same issue.
